# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: Git deploy to Heroku
      # You may pin to the exact commit or the version.
      # uses: onekiloparsec/heroku-node-deploy-subfolder@85d5701f800be8126e12b7f6f47e965c71f67b56
      uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
      with:
        # Your Heroku API key. This will be used for authentication. You can find it in your Heroku account settings
        api_key: ${{ secrets.HEROKU_API_KEY }}
        # The email of your Heroku account (needed for auth).
        email: ${{ secrets.EMAIL_ADDRESS }}
        # The app name to use for deploying/updating
        app_name: ${{ secrets.HEROKU_APP_NAME }}
        # The Heroku branch name that you would like to deploy to (`master` or `main`).
        heroku_branch: master
        # The subfolder where your built code is sitted, e.g. `dist`.
        subfolder: dist
